import { cleanClientLifecycleError, enrollClientForUser, listClientsForUser, prisma } from '@fitcrew/db';
import { auth } from '@/auth';
import { NextResponse } from 'next/server';
import { z } from 'zod';

const schema = z.object({ tenantId: z.string().uuid(), name: z.string().trim().min(1).max(200), email: z.string().trim().email().optional(), password: z.string().min(12).max(1024).optional(), price: z.union([z.string(), z.number()]), coachPartyId: z.string().uuid(), organizationId: z.string().uuid().nullable(), schedule: z.record(z.unknown()).default({}), photoConsent: z.boolean().default(false), subscriptionDurationMonths: z.number().int().positive().max(120) }).refine((value) => (!value.email && !value.password) || (value.email && value.password), { message: 'Email and password must be provided together.' });
export async function GET(request: Request) { const session = await auth(); const tenantId = new URL(request.url).searchParams.get('tenantId'); if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 }); if (!tenantId || !z.string().uuid().safeParse(tenantId).success) return NextResponse.json({ error: 'Invalid tenant.' }, { status: 400 }); try { return NextResponse.json(await listClientsForUser(prisma, tenantId, session.user.id)); } catch (error) { return NextResponse.json({ error: cleanClientLifecycleError(error) }, { status: 403 }); } }
export async function POST(request: Request) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 }); const parsed = schema.safeParse(await readJson(request)); if (!parsed.success) return NextResponse.json({ error: 'Invalid enrollment request.' }, { status: 400 }); try { return NextResponse.json(await enrollClientForUser(prisma, parsed.data.tenantId, session.user.id, parsed.data), { status: 201 }); } catch (error) { return NextResponse.json({ error: cleanClientLifecycleError(error) }, { status: 400 }); } }
async function readJson(request: Request): Promise<unknown> { try { return await request.json(); } catch { return null; } }
