import { cleanClientLifecycleError, enrollClientForUser, listClientPageForUser, listClientsForUser, prisma, reassignClientCoachForUser } from '@fitcrew/db';
import { auth } from '@/auth';
import { NextResponse } from 'next/server';
import { z } from 'zod';

const schema = z.object({ tenantId: z.string().uuid(), name: z.string().trim().min(1).max(200), email: z.string().trim().email().optional(), password: z.string().min(12).max(1024).optional(), price: z.union([z.string(), z.number()]), billingCadence: z.enum(['upfront', 'monthly']).default('monthly'), coachPartyId: z.string().uuid(), organizationId: z.string().uuid().nullable(), schedule: z.record(z.unknown()).default({}), photoConsent: z.boolean().default(false), subscriptionDurationMonths: z.number().int().positive().max(120) }).refine((value) => (!value.email && !value.password) || (value.email && value.password), { message: 'Email and password must be provided together.' });
const reassignSchema = z.object({ tenantId: z.string().uuid(), clientId: z.string().uuid(), coachPartyId: z.string().uuid(), reason: z.string().trim().max(500).optional() });
export async function PATCH(request: Request) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 }); const parsed = reassignSchema.safeParse(await readJson(request)); if (!parsed.success) return NextResponse.json({ error: 'Invalid coach assignment.' }, { status: 400 }); try { return NextResponse.json(await reassignClientCoachForUser(prisma, parsed.data.tenantId, session.user.id, parsed.data)); } catch (error) { return NextResponse.json({ error: cleanClientLifecycleError(error) }, { status: 400 }); } }
export async function GET(request: Request) { const session = await auth(); const url = new URL(request.url); const tenantId = url.searchParams.get('tenantId'); if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 }); if (!tenantId || !z.string().uuid().safeParse(tenantId).success) return NextResponse.json({ error: 'Invalid tenant.' }, { status: 400 }); try { const paged = url.searchParams.has('page') || url.searchParams.has('q'); return NextResponse.json(paged ? await listClientPageForUser(prisma, tenantId, session.user.id, { query: url.searchParams.get('q') ?? undefined, page: Number(url.searchParams.get('page') ?? 1), pageSize: Number(url.searchParams.get('pageSize') ?? 8) }) : await listClientsForUser(prisma, tenantId, session.user.id)); } catch (error) { return NextResponse.json({ error: cleanClientLifecycleError(error) }, { status: 403 }); } }
export async function POST(request: Request) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 }); const parsed = schema.safeParse(await readJson(request)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? 'Invalid enrollment request.' }, { status: 400 }); try { return NextResponse.json(await enrollClientForUser(prisma, parsed.data.tenantId, session.user.id, parsed.data), { status: 201 }); } catch (error) { return NextResponse.json({ error: cleanClientLifecycleError(error) }, { status: 400 }); } }
async function readJson(request: Request): Promise<unknown> { try { return await request.json(); } catch { return null; } }
