import { auth } from '@/auth';
import { changePasswordForUser, cleanProfileError, getProfileForUser, prisma, updateProfileForUser } from '@fitcrew/db';
import { NextResponse } from 'next/server';
import { z } from 'zod';
const profileSchema = z.object({ tenantId: z.string().uuid(), name: z.string().trim().min(1).max(120) });
const passwordSchema = z.object({ currentPassword: z.string().min(1), newPassword: z.string().min(12).max(1024) });
export async function GET(request: Request) { const session = await auth(); const tenantId = new URL(request.url).searchParams.get('tenantId'); if (!session?.user?.id || !tenantId) return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 }); try { return NextResponse.json(await getProfileForUser(prisma, tenantId, session.user.id)); } catch (error) { return NextResponse.json({ error: cleanProfileError(error) }, { status: 403 }); } }
export async function PATCH(request: Request) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 }); const parsed = profileSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: 'Invalid profile.' }, { status: 400 }); try { return NextResponse.json(await updateProfileForUser(prisma, session.user.id, parsed.data)); } catch (error) { return NextResponse.json({ error: cleanProfileError(error) }, { status: 400 }); } }
export async function POST(request: Request) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 }); const parsed = passwordSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: 'New password must be at least 12 characters.' }, { status: 400 }); try { return NextResponse.json(await changePasswordForUser(prisma, session.user.id, parsed.data.currentPassword, parsed.data.newPassword)); } catch (error) { return NextResponse.json({ error: cleanProfileError(error) }, { status: 400 }); } }
