'use client';

import { useMemo, useState } from 'react';

type Client = { clientId: string; name: string; organizationId: string | null; workflowState: string | null; photoConsent: boolean };
function initials(name: string) { return name.trim().split(/\s+/).filter(Boolean).slice(0, 2).map((word) => word[0]?.toUpperCase()).join('') || 'FC'; }

export function ClientList({ tenantId: _tenantId, clients }: { tenantId: string; clients: readonly Client[] }) {
  const [query, setQuery] = useState(''); const [stage, setStage] = useState('all'); const [page, setPage] = useState(1); const pageSize = 8;
  const stages = [...new Set(clients.map((client) => client.workflowState ?? 'Enrollment'))];
  const filtered = useMemo(() => clients.filter((client) => `${client.name} ${client.workflowState ?? 'Enrollment'}`.toLowerCase().includes(query.toLowerCase().trim()) && (stage === 'all' || (client.workflowState ?? 'Enrollment') === stage)), [clients, query, stage]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice((page - 1) * pageSize, page * pageSize);
  const search = (value: string) => { setQuery(value); setPage(1); }; const filter = (value: string) => { setStage(value); setPage(1); };
  return <><div className="directory-toolbar"><label className="directory-search"><span className="sr-only">Search clients</span><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => search(event.target.value)} placeholder="Search clients" /></label><label className="directory-filter"><span className="sr-only">Filter clients</span><select value={stage} onChange={(event) => filter(event.target.value)}><option value="all">All stages</option>{stages.map((value) => <option key={value} value={value}>{value}</option>)}</select></label></div><div className="directory-summary"><span>{filtered.length} {filtered.length === 1 ? 'client' : 'clients'}</span><span>{query || stage !== 'all' ? 'Filtered results' : 'Sorted by name'}</span></div>{visible.length ? <div className="client-list">{visible.map((client) => <article className="client-card" key={client.clientId}><div className="client-identity"><span className="client-roster-avatar" aria-hidden="true">{initials(client.name)}</span><div><h3>{client.name}</h3><p>{client.organizationId ? 'Organization client' : 'Direct client'}</p></div></div><div className="client-stage"><span>Onboarding</span><strong>{client.workflowState ?? 'Enrollment'}</strong></div><div className="client-consent"><span>Profile access</span><strong>{client.photoConsent ? 'Photo consented' : 'Standard access'}</strong></div><a className="secondary-button" href={`/clients/${client.clientId}`}>Open intake</a></article>)}</div> : <div className="client-empty-state"><strong>No clients match that search.</strong><p>Try a different name or clear the filters.</p></div>}{filtered.length > pageSize ? <nav className="directory-pagination" aria-label="Client pages"><span>Page {page} of {pageCount}</span><div><button className="pagination-button" onClick={() => setPage((current) => Math.max(1, current - 1))} disabled={page === 1}>Previous</button><button className="pagination-button" onClick={() => setPage((current) => Math.min(pageCount, current + 1))} disabled={page === pageCount}>Next</button></div></nav> : null}</>;
}
