import { effectiveAssignments } from '@fitcrew/application';
import { Prisma, PrismaClient } from '@prisma/client';
import { hashPassword, verifyPassword } from './password.js';
import { resolvePrincipal } from './access-gate.js';
import { withTenant, type TransactionCapableClient } from './with-tenant.js';
type Tx = Prisma.TransactionClient;
export class ProfileError extends Error {}
export async function getProfileForUser(prisma: PrismaClient, tenantId: string, userId: string) { return withTenant(prisma as unknown as TransactionCapableClient<Tx>, tenantId, async (tx) => { const principal = await resolvePrincipal(tx, tenantId, userId); if (!principal) throw new ProfileError('Forbidden.'); const party = await tx.party.findFirst({ where: { tenantId, userId }, include: { user: true } }); if (!party?.user) throw new ProfileError('Profile not found.'); const active = effectiveAssignments(principal); const isOwner = active.some((assignment) => assignment.role === 'OwnerAdmin' && assignment.scopeType === 'tenant'); const organizationIds = isOwner ? undefined : [...new Set(active.filter((assignment) => assignment.scopeType === 'organization' && assignment.scopeId).map((assignment) => assignment.scopeId!))]; const organizations = await tx.organization.findMany({ where: { tenantId, status: 'active', ...(organizationIds ? { id: { in: organizationIds } } : {}) }, include: { party: true }, orderBy: { party: { displayName: 'asc' } } }); const client = await tx.client.findFirst({ where: { tenantId, partyId: party.id } }); const clientOrg = client?.organizationId ? await tx.organization.findUnique({ where: { id: client.organizationId }, include: { party: true } }) : null; const assignment = client?.currentCoachAssignmentId ? await tx.clientCoachAssignment.findUnique({ where: { id: client.currentCoachAssignmentId } }) : null; const coach = assignment ? await tx.party.findUnique({ where: { id: assignment.coachPartyId } }) : null; return { user: { name: party.user.name, email: party.user.email, username: party.user.name ?? party.user.email.split('@')[0] ?? party.user.email }, role: [...new Set(active.map((assignment) => assignment.role))].join(', '), party: { displayName: party.displayName, contact: party.contact }, organizations: organizations.map((organization) => ({ id: organization.id, name: organization.party.displayName, status: organization.status })), client: client ? { organization: clientOrg?.party.displayName ?? null, coach: coach?.displayName ?? null, status: client.status } : null, coach: active.some((assignment) => assignment.role === 'Coach') ? { assignedOrganizationCount: organizations.length } : null }; }); }
export async function updateProfileForUser(prisma: PrismaClient, userId: string, input: { name: string }) { if (!input.name.trim()) throw new ProfileError('Username is required.'); return prisma.user.update({ where: { id: userId }, data: { name: input.name.trim().slice(0, 120) }, select: { name: true, email: true } }); }
export async function changePasswordForUser(prisma: PrismaClient, userId: string, currentPassword: string, newPassword: string) { if (newPassword.length < 12) throw new ProfileError('New password must be at least 12 characters.'); const user = await prisma.user.findUnique({ where: { id: userId }, select: { passwordHash: true } }); if (!user?.passwordHash || !(await verifyPassword(user.passwordHash, currentPassword))) throw new ProfileError('Current password is incorrect.'); await prisma.user.update({ where: { id: userId }, data: { passwordHash: await hashPassword(newPassword) } }); return { changed: true }; }
export function cleanProfileError(error: unknown) { return error instanceof ProfileError ? error.message : 'Profile update failed.'; }
