import { auth } from '@/auth';
import { cleanPaymentRecordingError, deletePayoutHandleForUser, prisma, savePayoutHandleForUser, updatePayoutHandleForUser } from '@fitcrew/db';
import { NextResponse } from 'next/server';
import { z } from 'zod';
const createSchema = z.object({ tenantId: z.string().uuid(), partyId: z.string().uuid(), type: z.enum(['upi', 'phone', 'qr']), value: z.string().min(1).max(500), label: z.string().max(100).optional(), isDefault: z.boolean().optional() });
const deleteSchema = z.object({ tenantId: z.string().uuid(), handleId: z.string().uuid() });
const updateSchema = createSchema.extend({ handleId: z.string().uuid() });
export async function POST(request: Request) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 }); const parsed = createSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: 'Invalid payout handle.' }, { status: 400 }); try { return NextResponse.json(await savePayoutHandleForUser(prisma, parsed.data.tenantId, session.user.id, parsed.data), { status: 201 }); } catch (error) { return NextResponse.json({ error: cleanPaymentRecordingError(error) }, { status: 400 }); } }
export async function DELETE(request: Request) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 }); const parsed = deleteSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: 'Invalid payout handle.' }, { status: 400 }); try { return NextResponse.json(await deletePayoutHandleForUser(prisma, parsed.data.tenantId, session.user.id, parsed.data.handleId)); } catch (error) { return NextResponse.json({ error: cleanPaymentRecordingError(error) }, { status: 400 }); } }
export async function PATCH(request: Request) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 }); const parsed = updateSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: 'Invalid payout handle.' }, { status: 400 }); try { return NextResponse.json(await updatePayoutHandleForUser(prisma, parsed.data.tenantId, session.user.id, parsed.data)); } catch (error) { return NextResponse.json({ error: cleanPaymentRecordingError(error) }, { status: 400 }); } }
