import { auth } from '@/auth';
import { cleanPaymentRecordingError, confirmPaymentForUser, getMoneyWorkspaceForUser, prisma, recordClientPaymentForUser, recordOrganizationPaymentForUser, reverseClientPaymentForUser, updateRefundClawbackRateForUser } from '@fitcrew/db';
import { NextResponse } from 'next/server';
import { z } from 'zod';
const tenant = z.string().uuid();
const method = z.enum(['upi', 'qr', 'phone', 'other']);
const recordSchema = z.discriminatedUnion('kind', [z.object({ kind: z.literal('client'), tenantId: tenant, subscriptionId: z.string().uuid(), amount: z.union([z.string(), z.number()]), method }), z.object({ kind: z.literal('organization'), tenantId: tenant, organizationId: z.string().uuid(), amount: z.union([z.string(), z.number()]), method })]);
const confirmSchema = z.object({ tenantId: tenant, paymentId: z.string().uuid(), utr: z.string().optional(), proofMediaAssetId: z.string().uuid().optional() });
const correctionSchema = confirmSchema.extend({ action: z.literal('reverse'), method });
const configSchema = z.object({ action: z.literal('config'), tenantId: tenant, refundCoachClawbackRate: z.union([z.string(), z.number()]) });
export async function GET(request: Request) { const session = await auth(); const tenantId = new URL(request.url).searchParams.get('tenantId'); if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 }); if (!tenantId || !tenant.safeParse(tenantId).success) return NextResponse.json({ error: 'Invalid tenant.' }, { status: 400 }); try { return NextResponse.json(await getMoneyWorkspaceForUser(prisma, tenantId, session.user.id)); } catch (error) { return NextResponse.json({ error: cleanPaymentRecordingError(error) }, { status: 403 }); } }
export async function POST(request: Request) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 }); const parsed = recordSchema.safeParse(await json(request)); if (!parsed.success) return NextResponse.json({ error: 'Invalid payment.' }, { status: 400 }); try { const result = parsed.data.kind === 'client' ? await recordClientPaymentForUser(prisma, parsed.data.tenantId, session.user.id, parsed.data) : await recordOrganizationPaymentForUser(prisma, parsed.data.tenantId, session.user.id, parsed.data); return NextResponse.json(result, { status: 201 }); } catch (error) { return NextResponse.json({ error: cleanPaymentRecordingError(error) }, { status: 400 }); } }
export async function PATCH(request: Request) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 }); const body = await json(request); try { const correction = correctionSchema.safeParse(body); if (correction.success) return NextResponse.json(await reverseClientPaymentForUser(prisma, correction.data.tenantId, session.user.id, correction.data)); const config = configSchema.safeParse(body); if (config.success) return NextResponse.json(await updateRefundClawbackRateForUser(prisma, config.data.tenantId, session.user.id, config.data.refundCoachClawbackRate)); const confirmation = confirmSchema.safeParse(body); if (confirmation.success) return NextResponse.json(await confirmPaymentForUser(prisma, confirmation.data.tenantId, session.user.id, confirmation.data)); return NextResponse.json({ error: 'Invalid money operation.' }, { status: 400 }); } catch (error) { return NextResponse.json({ error: cleanPaymentRecordingError(error) }, { status: 400 }); } }
async function json(request: Request): Promise<unknown> { try { return await request.json(); } catch { return null; } }
