import type { getOrgDashboardForUser } from '@fitcrew/db';
type Dashboard = Awaited<ReturnType<typeof getOrgDashboardForUser>>;

export function OrgDashboard({ data }: { data: Dashboard }) {
  return <>
    <header className="dashboard-header"><div><p className="eyebrow">Organization dashboard</p><h1>{data.organizations.length === 1 ? data.organizations[0]?.name : 'My organizations'}</h1><p className="muted">Read-only progress and coach team visibility for your members.</p></div></header>
    <section className="dashboard-summary"><article className="metric-card"><span>Members</span><strong>{data.kpis.members}</strong><small>Visible in your organization scope</small></article><article className="metric-card"><span>Sessions</span><strong>{data.kpis.sessionsLast30Days}</strong><small>Last 30 days</small></article><article className="metric-card"><span>Evaluations</span><strong>{data.kpis.evaluationsThisMonth}</strong><small>This month</small></article><article className="metric-card"><span>Attention needed</span><strong>{data.kpis.evaluationsDue}</strong><small>Evaluations due</small></article></section>
    <div className="dashboard-grid"><section className="surface"><div className="section-heading"><div><p className="eyebrow">Coach team</p><h2>Assigned coaches</h2></div></div><div className="data-list">{data.coaches.length ? data.coaches.map((coach) => <article className="data-row" key={coach.partyId}><div><h3>{coach.name}</h3><p className="muted">{coach.members} members</p></div></article>) : <p className="muted">No coaches assigned yet.</p>}</div></section><section className="surface"><div className="section-heading"><div><p className="eyebrow">Member signal</p><h2>Progress overview</h2></div><span className="status-label">{data.kpis.satisfaction === null ? 'No feedback yet' : `${data.kpis.satisfaction}/5 satisfaction`}</span></div><p className="muted">This view shows progress signals only. Financial details and private assessment content remain outside the organization role.</p>{data.kpis.evaluationsDue ? <p className="form-error" role="status">{data.kpis.evaluationsDue} member evaluation{data.kpis.evaluationsDue === 1 ? '' : 's'} due. Contact the assigned coach to coordinate follow-up.</p> : <p className="success-message">No evaluations are currently due.</p>}</section></div>
    <section className="surface"><div className="section-heading"><div><p className="eyebrow">Members</p><h2>Read-only progress</h2></div><span className="count-label">{data.members.length}</span></div><div className="data-list">{data.members.length ? data.members.map((member) => <article className="data-row" key={member.clientId}><div><h3>{member.name}</h3><p className="muted">Coach: {member.coach ?? 'Not assigned'} · {member.sessionsLast30Days} sessions in 30 days</p><p className="muted">{member.evaluationDue ? 'Evaluation due' : member.latestEvaluation ? `Last evaluation ${member.latestEvaluation}` : 'No evaluation recorded yet'}{member.satisfaction === null ? '' : ` · Satisfaction ${member.satisfaction}/5`}</p></div><span className="status-label">Read-only</span></article>) : <p className="muted">No members have been enrolled in this organization yet.</p>}</div></section>
    <p className="dashboard-refresh">Last refreshed {new Date(data.refreshedAt).toLocaleString('en-IN')} · {data.members.length} members visible</p>
  </>;
}
