'use client';

import { useMemo, useState } from 'react';
import { CoachTermsForm } from './terms-form';

type Coach = { engagementId: string; partyId: string; displayName: string; email: string | null; validFrom: string; commissionRate: string; commissionLifespanMonths: number };
function initials(name: string) { return name.trim().split(/\s+/).filter(Boolean).slice(0, 2).map((word) => word[0]?.toUpperCase()).join('') || 'FC'; }
export function CoachList({ tenantId, coaches }: { tenantId: string; coaches: readonly Coach[] }) {
  const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const pageSize = 8;
  const filtered = useMemo(() => coaches.filter((coach) => `${coach.displayName} ${coach.email ?? ''}`.toLowerCase().includes(query.toLowerCase().trim())), [coaches, query]); const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice((page - 1) * pageSize, page * pageSize); const search = (value: string) => { setQuery(value); setPage(1); };
  return <><div className="directory-toolbar"><label className="directory-search"><span className="sr-only">Search coaches</span><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => search(event.target.value)} placeholder="Search coaches" /></label><span className="directory-hint">Use a name or email</span></div><div className="directory-summary"><span>{filtered.length} {filtered.length === 1 ? 'coach' : 'coaches'}</span><span>{query ? 'Filtered results' : 'Sorted by name'}</span></div>{visible.length ? <div className="coach-list">{visible.map((coach) => <article className="coach-card" key={coach.engagementId}><div className="coach-identity"><span className="coach-avatar" aria-hidden="true">{initials(coach.displayName)}</span><div><h3>{coach.displayName}</h3><p>{coach.email ?? 'No email'}</p></div></div><div className="coach-meta"><span>Active from</span><strong>{coach.validFrom}</strong></div><CoachTermsForm tenantId={tenantId} engagementId={coach.engagementId} rate={coach.commissionRate} lifespan={coach.commissionLifespanMonths} /></article>)}</div> : <div className="coach-empty-state"><strong>No coaches match that search.</strong><p>Try a different name or email address.</p></div>}{filtered.length > pageSize ? <nav className="directory-pagination" aria-label="Coach pages"><span>Page {page} of {pageCount}</span><div><button className="pagination-button" onClick={() => setPage((current) => Math.max(1, current - 1))} disabled={page === 1}>Previous</button><button className="pagination-button" onClick={() => setPage((current) => Math.min(pageCount, current + 1))} disabled={page === pageCount}>Next</button></div></nav> : null}</>;
}
